# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-17 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinary_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_passWord', models.CharField(max_length=40)),
                ('account_mail', models.CharField(max_length=30)),
                ('nickname', models.CharField(default=' ', max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='images/')),
                ('true_name', models.CharField(max_length=30)),
                ('birth', models.DateField()),
                ('tel', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], max_length=6)),
            ],
            options={
                'db_table': 'ordinary_user',
                'ordering': ['id'],
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_pass', models.BooleanField(default=False)),
                ('user_label', models.CharField(default=None, help_text='备注信息', max_length=64)),
                ('friend_label', models.CharField(default=None, help_text='备注信息', max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加好友时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新分组时间')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend', to='client.Ordinary_User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='client.Ordinary_User')),
            ],
            options={
                'db_table': 'relationship',
                'ordering': ['id'],
            },
            managers=[
                ('relate', django.db.models.manager.Manager()),
            ],
        ),
    ]
