# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_name', models.CharField(max_length=100)),
                ('remark', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('riqi', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='date', to='client.Ordinary_User')),
            ],
            options={
                'db_table': 'date_table',
                'ordering': ['id'],
            },
        ),
    ]
