# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-17 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saying', models.TextField()),
                ('recevier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiv_comm', to='client.Ordinary_User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_comm', to='client.Ordinary_User')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['id'],
            },
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
